In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape

(3, 2)

In [8]:
import os
os.getcwd()

'/home/shivam/projects/coursera-ml-numpy/Week2'

In [23]:
featuresX = np.genfromtxt('featuresX.dat', delimiter=',')
priceY = np.genfromtxt('priceY.dat')

In [24]:
featuresX.shape, priceY.shape

((47, 2), (47,))

In [36]:
v = priceY[1:10]
v

array([329900., 369000., 232000., 539900., 299900., 314900., 198999.,
       212000., 242500.])

In [37]:
np.savetxt('hello.mat', v)

In [38]:
v = np.genfromtxt('hello.mat')

In [39]:
v

array([329900., 369000., 232000., 539900., 299900., 314900., 198999.,
       212000., 242500.])

In [68]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [44]:
A[2][1]

6

In [55]:
A[1,:]

array([3, 4])

In [56]:
A[:,1]

array([2, 4, 6])

In [58]:
A[(0, 2),:]

array([[1, 2],
       [5, 6]])

In [61]:
A[:,1] = [10, 11, 12]

In [62]:
A

array([[ 1, 10],
       [ 3, 11],
       [ 5, 12]])

In [70]:
A = np.hstack((A, [[100], [101], [102]]))

In [71]:
A

array([[  1,   2, 100],
       [  3,   4, 101],
       [  5,   6, 102]])

In [73]:
A.flatten()

array([  1,   2, 100,   3,   4, 101,   5,   6, 102])

In [74]:
A = [[1, 2], [3, 4], [5, 6]]
B = [[11, 12], [13, 14], [15, 16]]

In [80]:
np.hstack((A, B))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

In [81]:
np.vstack((A, B))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16]])