In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[11, 12], [13, 14], [15, 16]])
C = np.array([[1, 1], [2, 2]])

In [4]:
np.dot(A, C)

array([[ 5,  5],
       [11, 11],
       [17, 17]])

In [5]:
np.multiply(A, B)

array([[11, 24],
       [39, 56],
       [75, 96]])

In [11]:
A ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [12]:
v = np.array([[1], [2], [3]])

In [13]:
1 / v

array([[1.        ],
       [0.5       ],
       [0.33333333]])

In [14]:
1 / A

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ],
       [0.2       , 0.16666667]])

In [15]:
np.log(v)

array([[0.        ],
       [0.69314718],
       [1.09861229]])

In [16]:
np.exp(v)

array([[ 2.71828183],
       [ 7.3890561 ],
       [20.08553692]])

In [19]:
np.abs(np.array([[-1], [2], [-3]]))

array([[1],
       [2],
       [3]])

In [20]:
-v

array([[-1],
       [-2],
       [-3]])

In [28]:
v + np.ones((v.shape[1], 1))

array([[2.],
       [3.],
       [4.]])

In [29]:
v + 1

array([[2],
       [3],
       [4]])

In [30]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
np.transpose(A)

array([[1, 3, 5],
       [2, 4, 6]])

In [32]:
a = np.array([1, 15, 2, 0.5])

In [43]:
val, ind = np.max(a), np.argmax(a)
val, ind

(15.0, 1)

In [44]:
np.max(A)

6

In [45]:
a < 3

array([ True, False,  True,  True])

In [46]:
a[a < 3]

array([1. , 2. , 0.5])

In [52]:
np.where(a < 3)

(array([0, 2, 3]),)

In [72]:
# there's no function to generate a magic matrix in numpy
# we'll install another public package for it

In [73]:
%pip install magic_square

     |████████████████████████████████| 99 kB 1.6 MB/s eta 0:00:011
  Created wheel for magic-square: filename=magic_square-0.2-py3-none-any.whl size=6038 sha256=2cf9de38b50c2c799c9ac2bbde67d464b1c6283eb1ba8ade4b0fe6f154b6574f
  Stored in directory: /home/shivam/.cache/pip/wheels/4f/7c/bb/1eda87439a3720ba7bce946932f0115534d97d61c0ce9b176e
Successfully built magic-square
Note: you may need to restart the kernel to use updated packages.


In [78]:
from magic_square import magic
A = magic(3)

In [79]:
r, c = np.where(A >= 7)

In [80]:
r

array([0, 1, 2])

In [81]:
c

array([0, 2, 1])

In [82]:
A[1,2]

7

In [83]:
np.sum(a)

18.5

In [84]:
np.prod(a)

15.0

In [85]:
np.floor(a)

array([ 1., 15.,  2.,  0.])

In [86]:
np.ceil(a)

array([ 1., 15.,  2.,  1.])

In [87]:
np.maximum(np.random.rand(3, 3), np.random.rand(3, 3))

array([[0.21247548, 0.50764356, 0.65736798],
       [0.86944228, 0.67784593, 0.74171697],
       [0.67887174, 0.89145424, 0.7390116 ]])

In [88]:
A

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [89]:
np.max(A, axis=0)

array([8, 9, 7])

In [90]:
np.max(A, axis=1)

array([8, 7, 9])

In [91]:
A = magic(9)

In [92]:
A

array([[47, 58, 69, 80,  1, 12, 23, 34, 45],
       [57, 68, 79,  9, 11, 22, 33, 44, 46],
       [67, 78,  8, 10, 21, 32, 43, 54, 56],
       [77,  7, 18, 20, 31, 42, 53, 55, 66],
       [ 6, 17, 19, 30, 41, 52, 63, 65, 76],
       [16, 27, 29, 40, 51, 62, 64, 75,  5],
       [26, 28, 39, 50, 61, 72, 74,  4, 15],
       [36, 38, 49, 60, 71, 73,  3, 14, 25],
       [37, 48, 59, 70, 81,  2, 13, 24, 35]])

In [93]:
np.sum(A, axis=0)

array([369, 369, 369, 369, 369, 369, 369, 369, 369])

In [94]:
np.sum(A, axis=1)

array([369, 369, 369, 369, 369, 369, 369, 369, 369])

In [99]:
np.sum(np.multiply(A, np.eye(9)))

369.0

In [102]:
np.sum(np.multiply(A, np.flipud(np.eye(9))))

369.0

In [105]:
A = magic(3)
A

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [107]:
inv_A = np.linalg.pinv(A)
inv_A

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [109]:
np.dot(inv_A, A)  # equal to identity matrix

array([[ 1.00000000e+00,  2.77555756e-17, -2.94209102e-15],
       [-5.82867088e-15,  1.00000000e+00,  6.49480469e-15],
       [ 3.05311332e-15,  3.33066907e-16,  1.00000000e+00]])