In [1]:
import numpy as np

In [5]:
v = np.zeros((10, 1))
v

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [7]:
for i in range(1, 11):
    v[i-1] = 2**i
v

array([[   2.],
       [   4.],
       [   8.],
       [  16.],
       [  32.],
       [  64.],
       [ 128.],
       [ 256.],
       [ 512.],
       [1024.]])

In [8]:
indices = range(1, 11)
for i in indices:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [10]:
i = 1
while i <= 5:
    v [i-1] = 100
    i += 1
v

array([[ 100.],
       [ 100.],
       [ 100.],
       [ 100.],
       [ 100.],
       [  64.],
       [ 128.],
       [ 256.],
       [ 512.],
       [1024.]])

In [11]:
i = 1
while True:
    v[i-1] = 999
    i = i + 1
    if i == 6:
        break
v

array([[ 999.],
       [ 999.],
       [ 999.],
       [ 999.],
       [ 999.],
       [  64.],
       [ 128.],
       [ 256.],
       [ 512.],
       [1024.]])

In [12]:
v[0] = 2
if v[0] == 1:
    print('The value is one')
elif v[0] == 2:
    print('The value is two')
else:
    print('The value is not one or two.')

The value is two


In [14]:
def squareThisNumber(x):
    return x ** 2
squareThisNumber(5)

25

In [16]:
def squareAndCudeThisNumber(x):
    return x ** 2, x ** 3
a, b = squareAndCudeThisNumber(5)
a, b

(25, 125)

In [17]:
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([[1], [2], [3]])
θ = np.array([[0], [1]])

In [18]:
def costFunctionJ(X, y, θ):
    m = X.shape[0]
    predictions = np.dot(X, θ)
    sqrErrors = (predictions - y) ** 2
    return (1 / (2 * m)) * np.sum(sqrErrors)

In [19]:
costFunctionJ(X, y, θ)

0.0

In [20]:
θ = np.array([[0], [0]])
costFunctionJ(X, y, θ)

2.333333333333333